---
language: node_js

sudo: false

node_js:
- '0.10'
- '0.12'
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"

install:
  - npm install
